services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    networks:
      - minha-network
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    networks:
      - minha-network
    depends_on:
      - backend

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: bfer
      MYSQL_DATABASE: ultimos_campeoes
      MYSQL_USER: bfer
      MYSQL_PASSWORD: bfer
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - minha-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  mysql-data:

networks:
  minha-network:
    driver: bridge
